# -- Aliases

# Navigation
alias ..="cd .."
alias cd..="cd .."
alias ...="cd ~-"

# Display
alias l="ls -FalhBG"
alias ld="ls -ld */"
alias tree="find . | sed 's/[^/]*\//|   /g;s/| *\([^| ]\)/+--- \1/'"

# Shortcuts
alias c="clear"
alias q="exit"
alias h="history | tail -20"
alias duh="du -h --max-depth=1"
alias df="df -h"

# Implicit options
alias wget="wget -c"
alias mkdir="mkdir -pv"

# -- Prompt

bash_prompt() {

    # unsets color to term's fg color
    local NONE="\[\033[0m\]"

    # regular colors
    local K="\[\033[0;30m\]"    # black
    local R="\[\033[0;31m\]"    # red
    local G="\[\033[0;32m\]"    # green
    local Y="\[\033[0;33m\]"    # yellow
    local B="\[\033[0;34m\]"    # blue
    local M="\[\033[0;35m\]"    # magenta
    local C="\[\033[0;36m\]"    # cyan
    local W="\[\033[0;37m\]"    # white

    # emphasized (bolded) colors
    local EMK="\[\033[1;30m\]"
    local EMR="\[\033[1;31m\]"
    local EMG="\[\033[1;32m\]"
    local EMY="\[\033[1;33m\]"
    local EMB="\[\033[1;34m\]"
    local EMM="\[\033[1;35m\]"
    local EMC="\[\033[1;36m\]"
    local EMW="\[\033[1;37m\]"

    # background colors
    local BGK="\[\033[40m\]"
    local BGR="\[\033[41m\]"
    local BGG="\[\033[42m\]"
    local BGY="\[\033[43m\]"
    local BGB="\[\033[44m\]"
    local BGM="\[\033[45m\]"
    local BGC="\[\033[46m\]"
    local BGW="\[\033[47m\]"

    # user's color
    local UC=$Y
    # root's color
    [ $UID -eq "0" ] && UC=$EMR

    PS1="\n${UC}[${UC}\u${M}@${W}\h${UC}:${NONE}\#${UC}:${C}\${NEW_PWD}${UC}]\n${UC}➜${W} ${NONE}"
}

bash_prompt
unset bash_prompt

# -- shell/bash configuration

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Add tab completion for many Bash commands
if which brew > /dev/null && [ -f "$(brew --prefix)/etc/bash_completion" ]; then
    source "$(brew --prefix)/etc/bash_completion";
elif [ -f /etc/bash_completion ]; then
    source /etc/bash_completion;
fi;
